### ISSUE TITLE
Strings are not supported in the Show tag else, only tags are supported

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#1080]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [x] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroDRyYAWEA7nAL5wBmUEIcARAAIBGywANgCbpQB0wCAHoQwHKmCpGAbgBQc9AA9IsOL2oBDZJ3jVkAOwDGMIQbgBZAJ4BhepAPoDMABRg6YVAEpECuHCh0GGQocxc5f38AHm5gADcAPgjI%2FwRhACo4Awh4UmgAazh04SpklKjiMjhSIicAXgQYKGR0KnRODAaAcnaMOCMIZycYLooklJTUEnIBoecsnOqCssio4UrSJJXEDKWoQuLSibgK6eragwamlraO9AaY%2BITe9H7BmGG12MSx7cipqqzD7zPL7P5rDbjVbCb5QrzyChAA

### Expected Behaviour

When passing a string to `<Show>` tag else, compilation error.

```jsx
import { useStore, Show } from "@builder.io/mitosis";

export default function MyComponent(props) {

  return (
    <div>
      {/* not work */} 
      <Show when={true} else={'else content'}>
        show content not work
      </Show>

     {/* work */} 
      <Show when={true} else={<div>else content</div>}>
        show content work
      </Show>
    </div>
  );
}
```

### Actual Behaviour

Compilation error.

```log
react_devtools_backend.js:2655 TypeError: unknown: Cannot read properties of undefined (reading 'name')
    at e (574.46be52cca95735d1.js:1:42155)
    at e (574.46be52cca95735d1.js:1:42518)
    at Array.map (<anonymous>)
    at e (574.46be52cca95735d1.js:1:44174)
    at Be (574.46be52cca95735d1.js:1:49134)
    at n.FunctionDeclaration (574.46be52cca95735d1.js:1:57263)
    at r (218.40c6b86280210e15.js:2008:89915)
    at t._call (218.40c6b86280210e15.js:2008:18138)
    at t.call (218.40c6b86280210e15.js:2008:19517)
    at t.visit (218.40c6b86280210e15.js:2008:21204)
    at t.default.visitQueue (218.40c6b86280210e15.js:2008:13774)
    at t.default.visitQueue (218.40c6b86280210e15.js:2008:13832)
    at t.default.visitMultiple (218.40c6b86280210e15.js:2008:13411)
    at t.default.visit (218.40c6b86280210e15.js:2008:14023)
    at t.traverseNode (218.40c6b86280210e15.js:2008:87646)
    at t.visit (218.40c6b86280210e15.js:2008:21346)
    at t.default.visitQueue (218.40c6b86280210e15.js:2008:13774)
    at t.default.visitQueue (218.40c6b86280210e15.js:2008:13832)
    at t.default.visitSingle (218.40c6b86280210e15.js:2008:13479)
    at t.default.visit (218.40c6b86280210e15.js:2008:14049)
    at t.traverseNode (218.40c6b86280210e15.js:2008:87646)
    at d (218.40c6b86280210e15.js:2008:15159)
    at 218.40c6b86280210e15.js:13:10715
    at Generator.next (<anonymous>)
    at t.run (218.40c6b86280210e15.js:13:11027)
    at t.run.next (<anonymous>)
    at Function.<anonymous> (218.40c6b86280210e15.js:13:1884)
    at Generator.next (<anonymous>)
    at l (218.40c6b86280210e15.js:2008:756091)
    at Function.sync (218.40c6b86280210e15.js:2008:758120)
    at t.transform (218.40c6b86280210e15.js:13:1982)
    at fn (574.46be52cca95735d1.js:1:56276)
    at 574.46be52cca95735d1.js:1:380118
    at s (main-79e130091ee21132.js:1:86890)
    at Generator._invoke (main-79e130091ee21132.js:1:86678)
    at forEach.e.<computed> [as next] (main-79e130091ee21132.js:1:87313)
    at r (218.40c6b86280210e15.js:2008:3756359)
    at s (218.40c6b86280210e15.js:2008:3756562)
```

### Additional Information

Should support string in the Show tag else.

**Comment by samijaber** [comment]
I don't think this is an issue in every generator. It is per-generator most likely, based on how each generator generates the children of `Show`.

In the case of React outputs:

https://github.com/BuilderIO/mitosis/blob/e6d4d0d18a9e2fecd4a2c32d6a48d9a10a93477c/packages/core/src/generators/react/helpers.ts#L24

This check should instead be something like:

```
json.children.length !== 1 && !isRootTextNode(json)
```

to also add fragments when there's 1 text node

**Comment by samijaber** [comment]
The error is here:

https://github.com/BuilderIO/mitosis/blob/8b4f9b7085af7457041333157a1cb1bf078a3b22/packages/core/src/parsers/jsx/element-parser.ts#L138-L142

We might need to change what we provide to `jsxtoElementJson`: I tried `jsxElementToJson(elseAttr.value)` but that caused other issues. 🤔
