### ISSUE TITLE
Solid compilation target fails on the "basic" example

### ISSUE THREAD

**Issue by L1lith** [BuilderIO/mitosis#407]
- [?] I am interested in helping provide a fix
If I have the skills to fix this I wouldn't mind looking around when I get time. I don't really understand the Solid internals fully though.

**Describe the bug**
The [basic example](https://github.com/BuilderIO/mitosis/tree/main/examples/basic) fails when the `mitosis.config.js` has it's target changed to Solid

mitosis.config.js
```js
const seedrandom = require('seedrandom');
const rng = seedrandom('vue-sdk-seed');

const getSeededId = () => {
  const rngVal = rng();
  return Number(String(rngVal).split('.')[1]).toString(36);
};

module.exports = {
  files: 'src/**',
  targets: ['solid'],
};
```

**To Reproduce**
1. Setup the example
2. Change the target
3. Run `npm start` in CLI

**Expected behavior**
Should compile the basic example into Solid components (but it errors out instead)

## ERROR MESSAGE
```bash
HOME_USER$ npm start

> start
> watch 'npm run mitosis' ./src ./overrides

> Watching ./src
> Watching ./overrides

> mitosis
> mitosis build

/Users/HOME_USER/basic/node_modules/gluegun/build/index.js:15
    throw up;
    ^

SyntaxError: Expression expected. (10:5)
   8 |   return (
   9 |     
> 10 |     )
     |     ^
  11 | }
    at r (/Users/HOME_USER/basic/node_modules/prettier/parser-typescript.js:1:557)
    at yx (/Users/HOME_USER/basic/node_modules/prettier/parser-typescript.js:13:3304376)
    at Object.parse (/Users/HOME_USER/basic/node_modules/prettier/parser-typescript.js:13:3304817)
    at Object.parse (/Users/HOME_USER/basic/node_modules/prettier/standalone.js:1:201395)
    at qD (/Users/HOME_USER/basic/node_modules/prettier/standalone.js:1:225602)
    at JD (/Users/HOME_USER/basic/node_modules/prettier/standalone.js:1:228265)
    at /Users/HOME_USER/basic/node_modules/prettier/standalone.js:40:40390
    at format (/Users/HOME_USER/basic/node_modules/prettier/standalone.js:40:40474)
    at /Users/HOME_USER/basic/node_modules/@builder.io/mitosis/dist/src/generators/solid.js:179:43
    at /Users/HOME_USER/basic/node_modules/@builder.io/mitosis-cli/dist/build/build.js:301:180 {
  loc: { start: { line: 10, column: 5 } },
  codeFrame: '   8 |   return (\n   9 |     \n> 10 |     )\n     |     ^\n  11 | }'
  ```

**Comment by vamseekrishna9** [comment]
This answer may be helpful to you. Please refer here https://github.com/BuilderIO/mitosis/issues/350#issuecomment-1128160728
